sudo: false

language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"

env:
  global:
    - TEST_DIR=/tmp/hmmlearn
    - COVERAGE=`[[ $TRAVIS_PYTHON_VERSION = "2.7" ]] && echo true || echo false`

install: source continuous_integration/travis/install.sh
script: bash continuous_integration/travis/test_script.sh
after_success: source continuous_integration/travis/after_success.sh
